require('jquery')
require('popper.js')
require('bootstrap')
require('bootstrap/dist/css/bootstrap.min.css')
require('video.js')
require('video.js/dist/video-js.css')
require('@videojs/http-streaming')
require('./style.scss')
const brandLogo = require('./pMediaNodeLogo.svg')

document.querySelector("#brandLogo").setAttribute('src', '/assets/' + brandLogo)